### ISSUE TITLE
KeysValue中能否添加json_keys

### ISSUE THREAD

**Issue by NinePure** [aliyun/alibabacloud-java-sdk#26]
json类型的索引底下有很多json_keys, 现在用sdk去同步两个地区的索引时,json内部的值同步不过来,希望能优化一下
(我目前的操作, 从A LogStore获取索引keys, 然后更新到B LogStore上, json类型底下的参数同步不了)

**Comment by TsinghuaDream** [comment]
业务需求问题，请工单反馈给SLS的同学https://smartservice.console.aliyun.com/service/create-ticket
