### ISSUE TITLE
dubbo传参BatchQueryDeviceDetailRequest需要序列化

### ISSUE THREAD

**Issue by tomsue** [aliyun/alibabacloud-java-sdk#4]
` <groupId>com.aliyun</groupId>
<artifactId>iot20180120</artifactId>
`
TeaModel 需要序列化，否则不支持dubbo传参
com.aliyun.iot20180120.models.BatchQueryDeviceDetailRequest extends com.aliyun.tea.TeaModel

**Comment by JacksonTian** [comment]
@tomsue 抱歉没有注意到这个 issue。看起来我们的 teamodel 是会支持序列化的。

因为时间比较久，这个 issue 会先关闭。如果仍然有问题，可以 re-open。也可以通过钉钉服务群来继续沟通：60965016010。
